---
- name: Install Apache Tomcat
  hosts: webservers
  become: yes  # If you need root privileges to install packages
  tasks:

    - name: Download Tomcat tar.gz
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.34/bin/apache-tomcat-10.1.34.tar.gz"
        dest: "/tmp/apache-tomcat-10.1.34.tar.gz"

    - name: Extract Tomcat tar.gz
      unarchive:
        src: "/tmp/apache-tomcat-10.1.34.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Set correct permissions for Tomcat
      file:
        path: "/opt/apache-tomcat-10.1.34"
        owner: tomcat
        group: tomcat
        mode: '0755'
        recurse: yes

    - name: Create a systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Tomcat 10 servlet container
          After=network.target

          [Service]
          User=tomcat
          Group=tomcat
          ExecStart=/opt/apache-tomcat-10.1.34/bin/catalina.sh run
          ExecStop=/opt/apache-tomcat-10.1.34/bin/catalina.sh stop
          Type=forking
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply changes
      systemd:
        daemon_reload: yes

    - name: Enable Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: started
